spring:
  application:
    name: del-app
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/delapp?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect